### ISSUE TITLE
OptionalDouble/Int/Long not managed as Optional

### ISSUE THREAD

**Issue by lvjp** [inferred/FreeBuilder#304] opened 2018-10-27 20:08 UTC
The `OptionalDouble/Int/Long` are not fully work like `Optional<Double>` but with native type.

With the input :
```java
@FreeBuilder
public interface MyOptionalData {
  OptionalInt number();
  class Builder extends MyOptionalData_Builder{}
}
```
I didn't have methods like `public Builder number(int){...}` in the created builder like for the `Optional` class.

**Comment by alicederyn** [comment] 2018-10-29 13:37
Duplicate of #171.

**Closed by alicederyn** 2018-10-29 13:37 UTC

**Comment by alicederyn** [comment] 2019-01-24 13:58
FreeBuilder now supports primitive optionals as of [v2.2](https://github.com/inferred/FreeBuilder/releases/tag/v2.2.0).
