### ISSUE TITLE
IgnoredByEquals doesn't work

### ISSUE THREAD

**Issue by artieshevchenko** [inferred/FreeBuilder#431] opened 2020-05-19 05:00 UTC
I tried versions 2.4.1 and 2.6.1 but it didn't work in both of them. So I had to manually correct equals/hashcode in the generated code.

The use is straightforward, so I'm not sure if you want to see the original code, but here it is without any dependencies/imports:

```
@FreeBuilder
public interface StorageUnitMetric {

  String getLocalSpaceCode();

  String getEventTypesConfig();

  /**
   * Internal field for analytics and future reference. When stored in DB it is not necessarily the
   * same metric ID as the metric you query. It is not even read from DB btw.
   */
  @IgnoredByEquals
  Optional<Long> getOriginalMetricIdOpt();

  long getChronologicalSnobberyMillis();

  boolean isNormalized();

  long getContextTypeId();

  long getExpectationInstantMillis();

  String getBasisUpdateEpochMillisByContextIdSorted();

  long getUnitId();

  ImmutableList<PeriodSpanSpec> getSortedPeriodSpanSpecs();

  class Builder extends StorageUnitMetric_Builder {}
}
```

**Comment by alicederyn** [comment] 2020-05-20 14:17
@thespags Could you take a look at this? (No good deed goes unpunished and all!)

**Comment by thespags** [comment] 2020-05-20 19:31
@artieshevchenko Can you provide inputs that fails your expectation?

I tried these scenarios (exactly your class except the list with periodspanspec removed.
```
        final StorageUnitMetric.Builder builder = new StorageUnitMetric.Builder()
            .setLocalSpaceCode("someLocalSpaceCode")
            .setEventTypesConfig("someEventTypesConfig")
            .setChronologicalSnobberyMillis(1234)
            .setNormalized(true)
            .setContextTypeId(5678)
            .setExpectationInstantMillis(4567)
            .setBasisUpdateEpochMillisByContextIdSorted("someBasisUpdate")
            .setUnitId(0123);
        final StorageUnitMetric withNoMetricId = builder.build();
        final StorageUnitMetric otherWithNoMetric = builder.build();
        final StorageUnitMetric withMetricId123 = builder
            .setOriginalMetricIdOpt(123)
            .build();
        final StorageUnitMetric otherWithMetricId123 = builder
            .setOriginalMetricIdOpt(123)
            .build();
        final StorageUnitMetric withMetricId246 = builder
            .setOriginalMetricIdOpt(246)
            .build();
        System.err.println(Objects.equals(withNoMetricId, otherWithNoMetric));
        System.err.println(Objects.equals(withNoMetricId, withMetricId123));
        System.err.println(Objects.equals(withNoMetricId, withMetricId246));
        System.err.println(Objects.equals(withMetricId123, otherWithMetricId123));
        System.err.println(Objects.equals(withMetricId123, withMetricId246));
```
and the output is true, for each case since metric id is not to be considered into the evaluation. If I change another field, then cases will evaluate to false appropriately.

**Comment by artieshevchenko** [comment] 2020-05-21 00:18
Hm, let's leave just two fields there, for simplicity reasons:

```
import java.util.Optional;
import org.inferred.freebuilder.FreeBuilder;
import org.inferred.freebuilder.IgnoredByEquals;

@FreeBuilder
public interface StorageUnitMetric2 {

  String getLocalSpaceCode();

  @IgnoredByEquals
  Optional<Long> getOriginalMetricIdOpt();

  class Builder extends StorageUnitMetric2_Builder {}
}

```

Here is my ```pom.xml``` entry:

```
<dependency>
        <groupId>org.inferred</groupId>
        <artifactId>freebuilder</artifactId>
        <version>2.6.1</version>
      </dependency>
```

I generate the following code by compiling StorageUnitMetric in IntelliJ IDEA. Here is the equals/hashCode code it generated for me:

```
@Override
    public boolean equals(Object obj) {
      if (!(obj instanceof StorageUnitMetric2_Builder.Partial)) {
        return false;
      }
      StorageUnitMetric2_Builder.Partial other = (StorageUnitMetric2_Builder.Partial) obj;
      return Objects.equals(localSpaceCode, other.localSpaceCode)
          && Objects.equals(originalMetricIdOpt, other.originalMetricIdOpt)
          && Objects.equals(_unsetProperties, other._unsetProperties);
    }

    @Override
    public int hashCode() {
      return Objects.hash(localSpaceCode, originalMetricIdOpt, _unsetProperties);
    }
```

I guess the generated code should look different, right? Just to make sure we're on the same page, here is your test:

```
    StorageUnitMetric2.Builder builder = new StorageUnitMetric2.Builder().setLocalSpaceCode("1");

    final StorageUnitMetric2 withNoMetricId = builder.build();
    final StorageUnitMetric2 otherWithNoMetric = builder.build();
    final StorageUnitMetric2 withMetricId123 = builder.setOriginalMetricIdOpt(123).build();
    final StorageUnitMetric2 otherWithMetricId123 = builder.setOriginalMetricIdOpt(123).build();
    final StorageUnitMetric2 withMetricId246 = builder.setOriginalMetricIdOpt(246).build();

    System.err.println(Objects.equals(withNoMetricId, otherWithNoMetric));
    System.err.println(Objects.equals(withNoMetricId, withMetricId123));
    System.err.println(Objects.equals(withNoMetricId, withMetricId246));
    System.err.println(Objects.equals(withMetricId123, otherWithMetricId123));
    System.err.println(Objects.equals(withMetricId123, withMetricId246));
```

Test results:

```
true
false
false
true
false
```

**Comment by artieshevchenko** [comment] 2020-05-21 00:37
Oops, never mind - that was an IntelliJ project configuration problem. IntelliJ was using an old version of FreeBuilder as a global library. It's weird that it compiled @IgnoredByEquals as I guess it should be new, but that's another story. Thanks for looking into this, @thespags!

**Comment by thespags** [comment] 2020-05-21 00:39
Cool no worries. I just confirmed that the generated equals looks good  (see below) and I was going to ask if intellij was using an old version of freebuilder. (that happens to me with dependencies in intellij from time to time being stale from whats in the pom)

```
    @Override
    public boolean equals(Object obj) {
      if (!(obj instanceof Partial)) {
        return false;
      }
      Partial other = (Partial) obj;
      return Objects.equals(localSpaceCode, other.localSpaceCode)
          && Objects.equals(_unsetProperties, other._unsetProperties);
    }
```

**Comment by alicederyn** [comment] 2020-05-21 17:20
Thanks @thespags ! Closing out.

**Closed by alicederyn** 2020-05-21 17:20 UTC
Labels: bug
